package com.holotrash.lazerdeath2;

public enum WeaponType {
	LAZER_LV1, 
	LAZER_LV2, 
	LAZER_LV3, 
	PARTICLE_BEAM_LV1, 
	PARTICLE_BEAM_LV2, 
	PARTICLE_BEAM_LV3, 
	PSIONIC_WILL_LV1, 
	PSIONIC_WILL_LV2,
	PSIONIC_WILL_LV3,
	PHASE_BLUDGEON_LV1,
	PHASE_BLUDGEON_LV2,
	PHASE_BLUDGEON_LV3,
	LAZER_FIST_LV1,
	LAZER_FIST_LV2,
	TISSUE_REPLICATOR_LV1,
	TISSUE_REPLICATOR_LV2,
	TISSUE_REPLICATOR_LV3
}
